### ISSUE TITLE
Lowest numpy version to use with storey?

### ISSUE THREAD

**Issue by Larleyt** [mlrun/storey#224]
The `~=` definition to all dependencies is kinda unclear. What is the lowest numpy version that can be used with `storey` package? Which `storey` version supports `numpy==1.18.5`?

**Comment by dinal** [comment]
Hi @Larleyt, As of v0.5.2 we changed storey's numpy requirement to accept a wider range of versions - numpy>=1.16.5, <1.20.0
before that only 1.19.x versions were supported

**Comment by gtopper** [comment]
Regarding the `~=` notation itself, see https://www.python.org/dev/peps/pep-0440/#compatible-release.
